### PR TITLE
Update Podfile

### PR DESCRIPTION
**Pull request by jeffreyjackson**
No need for Facebook SDK pod since it is already called as a dependency for Parse pod.

### CODE REVIEW

**Comment by jeffreyjackson** [comment]
hey @hramos - it probably makes sense to merge this one too since you already did #54.  Should just need to remove the facebook pod from the Podfile, since Parse pod pulls in the facebook pod automatically.  :beers:

**Comment by hramos** [comment]
@jeffreyjackson the PR looks good, just a quick comment before it's merged in: the reason that the Facebook-iOS-SDK pod can be removed from the podfile is that the ParseFacebookUtils pod, not the Parse pod, is the one that declares Facebook-iOS-SDK as a dependency.

Parse podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/Parse/1.6.4/Parse.podspec.json

ParseFacebookUtils podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/ParseFacebookUtils/1.6.4/ParseFacebookUtils.podspec.json

**Comment by hramos** [comment]
Can you take a look at the merge conflicts?

**Comment by jeffreyjackson** [comment]
Sure thing, I'll have it resolved tonight!

**Pull request closed without merging**
